class ders{
  static const lessons_list=[
    'Yabancı Dil 1',
    'Türk Dili 1',
    'Fizik 1',
    'Matematik 1',
    'Bilişim Teknolojileri',
    'Lineer Cebir',
    'Algoritma ve Programlama 1',
    'Bilgisayar Müh. Giriş',
    'Yabancı Dil 2',
    'Türk Dili 2',
    'Fizik 2',
    'Matematik 2',
    'Algoritma ve Programlama 2',
    'Mühendislik Etiği',
    'Elektrik Devreleri ve Elektronik',
    'İş Sağlığı ve Güvenliği',
    'Kariyer Planlama',
    'Ayrık İşlemsel Yapılar',
    'Sayısal Elektronik',
    'Mühendislik Matematiği',
    'Mesleki Yabancı Dil 1',
    'Atatürk İlke ve İnkılap Tarihi 1',
    'Serbest Seçmeli Ders',
    'Olasılık ve İstatistik',
    'Programlama Dil. Prensip.',
    'Bilgisayar Organizasyonu',
    'Nesneye Dayalı Programlama',
    'Mesleki Yabancı Dil 2',
    'Atatürk İlke ve İnkılap Tarihi 2',
    'Staj 1',
    'Serbest Seçmeli Ders 2',
    'Biçimsel Dil. ve Soyut Makine.',
    'Sinyal ve Sistemler',
    'İşletim Sistemleri',
    'Veritabanı Yönetim Sistem',
    'Mühendislik Ekonomisi',
    'Algoritma Analizi',
    'Serbest Seçmeli Ders 3',
    'Mikroişlemciler',
    'Sistem Programlama',
    'Yazılım Mühendisliği',
    'İnternet Teknolojileri',
    'Bilgisayar Ağları',
    'Sosyal Seçmeli Ders',
    'Bil. Müh. Proje Tasarımı',
    'Girişimcilik ve Liderlik',
    'Mesleki Seçmeli Ders',
    'Diploma Çalışması',
  ];

}
